create database santa_rosa;
use santa_rosa;
set sql_mode='';

create table cliente(
	id_cliente int not null auto_increment primary key,
	nombre varchar(255),
	apellido varchar(255),
	dni varchar(255),
	telefono varchar(255),
	direccion varchar(255),
	sexo varchar(255),
	-- usuario varchar(255),
	email varchar(255),
	-- password varchar(500),
	mensaje varchar(500),
	imagen varchar(500),
	is_activo boolean default 1,
	is_admin boolean default 0,
    is_publico boolean default 0,
	is_proveedor boolean default 0,
	fecha datetime,
	fechaactualizacion datetime
);
create table usuario(
	id_usuario int not null auto_increment primary key,
	nombre varchar(255),
	apellido varchar(255),
   	direccion varchar(255),
   	genero varchar(255),
   	email varchar(255),
    -- profesion varchar(255),
    dni varchar(255),
    telefono varchar(255),
    imagen varchar(500),
	usuario varchar(255),
	password varchar(255),
    nivel int,
	cargo varchar(255),
	fecha_nacemiento date,
	otros varchar(255),
	is_activo boolean default 1,
	is_admin boolean default 0,
   	is_publico boolean default 0,
	fecha datetime,
	fechaactualizacion datetime
);
insert into usuario(nombre,
apellido,
direccion,
genero,
email,
-- profesion,
dni,
telefono,
imagen,
usuario,
password,
nivel,
cargo,
fecha_nacemiento,
otros,
is_activo,
is_admin,
is_publico,
fecha,
fechaactualizacion)value ("Admin1",
"Anonimo",
"",
"",
-- "",
"",
"",
"",
"",
"admin1",
"90b9aa7e25f80cf4f64e990b78a9fc5ebd6cecad",
"1",
"",
"",
"",
"1",
"1",
"0",
NOW(),
"");
insert into usuario(nombre,
apellido,
direccion,
genero,
email,
-- profesion,
dni,
telefono,
imagen,
usuario,
password,
nivel,
cargo,
fecha_nacemiento,
otros,
is_activo,
is_admin,
is_publico,
fecha,
fechaactualizacion)value ("Admin2",
"Anonimo",
"",
"",
-- "",
"",
"",
"",
"",
"admin2",
"90b9aa7e25f80cf4f64e990b78a9fc5ebd6cecad",
"1",
"",
"",
"",
"1",
"1",
"0",
NOW(),
"");

create table empresa(
	id_empresa int not null auto_increment primary key,
	usuario_id int,
	nombre varchar(100),
	descripcion varchar(500),
	direccion varchar(100),
	calidad varchar(500),
	seguridad varchar(500),
	garantia varchar(500),
	mision varchar(500),
	vision varchar(500),
	valores varchar(500),
	horario_atencion varchar(500),
	logo varchar(500),
	imagen varchar(500),
	gerente varchar(500),
	texto1 varchar(500),
	texto2 varchar(500),
	texto3 varchar(500),
	texto4 varchar(500),
	texto5 varchar(500),
	texto6 varchar(500),
	footer1 varchar(500),
	footer2 varchar(500),
	footer3 varchar(500),
	telefono varchar(500),
	ciudad varchar(500),
	pais varchar(50),
	email varchar(50),
	red_social1 varchar(500),
	red_social2 varchar(500),
	red_social3 varchar(500),
	red_social4 varchar(500),
	red_social5 varchar(500),
	red_social6 varchar(500),
	red_social7 varchar(500),
	is_activo boolean default 1,
   	is_publico boolean default 0,
	fecha datetime,
	fechaactualizacion datetime,
	-- foreign key (cliente_id) references cliente(id_cliente),
	foreign key (usuario_id) references usuario(id_usuario)
	-- foreign key (configuracion_id) references configuracion(id_configuracion)
);
insert into empresa(nombre,
descripcion,
direccion,
calidad,
seguridad,
garantia,
mision,
vision,
valores,
horario_atencion,
logo,
imagen,
gerente,
texto1,
texto2,
texto3,
texto4,
texto5,
texto6,
footer1,
footer2,
footer3,
telefono,
ciudad,
pais,
email,
red_social1,
red_social2,
red_social3,
red_social4,
red_social5,
red_social6,
red_social7,
is_activo,
is_publico,
fecha,
fechaactualizacion)
value ("SANTA ROSA",
	"Sistema Cajahuaman",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	".: SANTA R :.",
	"SII",
	"NOOO",
	"J-SOLUTION",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	NOW(),
	"");

-- create table precio(
-- id_precio int not null auto_increment primary key,
-- nombre varchar(500),
-- precio float,
-- descripcion varchar(500),
-- is_activo boolean default 1,
-- is_publico boolean default 0
-- );
create table pago(
id_pago int not null auto_increment primary key,
nombre float,
descripcion varchar(500)
);
insert into pago (nombre,descripcion) value ("1.50","");
insert into pago (nombre,descripcion) value ("2","");
insert into pago (nombre,descripcion) value ("4","");
insert into pago (nombre,descripcion) value ("5","");
insert into pago (nombre,descripcion) value ("10","");

create table fecha(
	id_fecha int not null auto_increment primary key,
	fechaentrada TIMESTAMP(0) null default CURRENT_TIMESTAMP,
	fechasalida TIMESTAMP(0) null default CURRENT_TIMESTAMP,
	resultado decimal(7,2),
	precio float
);

create table caja(
	id_caja int not null auto_increment primary key,
	fecha datetime
);
create table cajalavanderia(
	id_cajalavanderia int not null auto_increment primary key,
	fecha datetime
);
create table accion(
	id_accion int not null auto_increment primary key,
	nombre varchar(50)
);

insert into accion (nombre) value ("entrada");
insert into accion (nombre) value ("salida");

create table actividad(
	id_actividad int not null auto_increment primary key,
	nombre varchar(50)
);

insert into actividad (nombre) value ("lavandero");
insert into actividad (nombre) value ("cochera");

create table vehiculo(
id_vehiculo int not null auto_increment primary key,
cliente_id int,
nombre varchar(500),
marca varchar(500),
modelo varchar(500),
tipo_vehiculo varchar(500),
matricula varchar(500),
color varchar(500),
serie varchar(500),
placa varchar(500),
generacion varchar(500),
equipamiento varchar(500),
descripcion varchar(500),
detalle varchar(500),
imagen varchar(1000),
is_activo boolean default 1,
is_publico boolean default 0,
in_inicio boolean default 0,
fecha datetime,
fechaactualizacion datetime,
foreign key (cliente_id) references cliente(id_cliente)
);

create table proceso(
id_proceso int not null auto_increment primary key,
vehiculo_id int,
pago_id int,
usuario_id int,
cliente_id int,
fecha_id int,
accion_id int,
actividad_id int,
dni varchar(500),
placa varchar(500),
descripcion varchar(500),
total float,
cash float,
q float,
cantidad float,
desminuir float,
impuesto float,
pago boolean default 0,
-- fecha_salida datetime,
-- fecha_ingreso datetime,
fecha_salida TIMESTAMP(0) null default CURRENT_TIMESTAMP,
fecha_ingreso TIMESTAMP(0) null default CURRENT_TIMESTAMP,
cantidad_hora float,
cantidad_dia float,
contar_fecha float,
fecha datetime,
foreign key (vehiculo_id) references vehiculo(id_vehiculo),
foreign key (pago_id) references pago(id_pago),
foreign key (usuario_id) references usuario(id_usuario),
foreign key (cliente_id) references cliente(id_cliente),
foreign key (fecha_id) references fecha(id_fecha),
foreign key (accion_id) references accion(id_accion),
foreign key (actividad_id) references actividad(id_actividad)
);

create table operacion(
	id_operacion int not null auto_increment primary key,
	vehiculo_id int,
	accion_id int,
	proceso_id int,
	actividad_id int,
	pago_id int,
	caja_id int,
	cajalavanderia_id int,
	subtotal float,
	q float,
	actividad varchar(500),
	dni varchar(500),
	placa varchar(500),
	dueno varchar(500),
	impuesto float,
	descuento float,
	cantidad float,
	fecha datetime,
	foreign key (vehiculo_id) references vehiculo(id_vehiculo),
	foreign key (accion_id) references accion(id_accion),
	foreign key (proceso_id) references proceso(id_proceso),
	foreign key (actividad_id) references actividad(id_actividad),
	foreign key (pago_id) references pago(id_pago),
	foreign key (caja_id) references caja(id_caja),
	foreign key (cajalavanderia_id) references cajalavanderia(id_cajalavanderia)
);


-- ----------------------------------------------------------------------------
-- create table personal(
-- 	id_personal int not null auto_increment primary key,
-- 	nombre varchar(255),
-- 	apellido varchar(255),
--    	direccion varchar(255),
--    	genero varchar(255),
--    	email varchar(255),
--     profesion varchar(255),
--     dni varchar(255),
--     telefono varchar(255),
-- 	base varchar(500),
--     curriculum varchar(500),
--     imagen varchar(500),
--     hora_inicio_labor time,
--     fecha_inicio_labor date,
-- 	hora_final_labor time,
--     fecha_final_labor date,
--    	horario_trabajo varchar(255),
-- 	usuario varchar(255),
-- 	password varchar(255),
-- 	convocatoria varchar(255),
--     nivel int,
-- 	codigo_asistencia varchar(255),
-- 	entrada varchar(255),
-- 	salida varchar(255),
-- 	area varchar(255),
-- 	cargo varchar(255),
-- 	mensaje varchar(255),
-- 	comentario1 varchar(500),
-- 	comentario2 varchar(500),
-- 	comentario3 varchar(500),
-- 	comentario4 varchar(500),
-- 	comentario5 varchar(500),
-- 	comentario6 varchar(500),
-- 	nota varchar(500),
-- 	fecha_nacemiento date,
-- 	satesfaccion_trabajo varchar (500),
-- 	calificacion1 boolean default 0,
-- 	calificacion2 boolean default 0,
-- 	calificacion3 boolean default 0,
-- 	calificacion4 boolean default 0,
-- 	calificacion5 boolean default 0,
-- 	datos_deseado varchar(255),
-- 	cod_asistencia varchar(500),
-- 	experiencia varchar(500),
-- 	fase_evaluacion boolean default 0,
-- 	sueldodeseado float,
-- 	sueldo float,
-- 	otros varchar(255),
-- 	is_active boolean default 1,
-- 	is_admin boolean default 0,
--    	is_publico boolean default 0,
-- 	esta_aprobado boolean default 0,
-- 	postulante boolean default 1,
-- 	ingresadopor boolean default 1,
-- 	desaprobado boolean default 0,
-- 	fecha datetime,
-- 	fechaaprobado datetime,
-- 	fechaactualizacion datetime

-- );
-- insert into personal(nombre,
-- apellido,
-- direccion,
-- genero,
-- email,
-- profesion,
-- dni,
-- telefono,
-- base,
-- curriculum,
-- imagen,
-- hora_inicio_labor,
-- fecha_inicio_labor,
-- hora_final_labor,
-- fecha_final_labor,
-- horario_trabajo,
-- usuario,
-- password,
-- convocatoria,
-- nivel,
-- codigo_asistencia,
-- entrada,
-- salida,
-- area,
-- cargo,
-- mensaje,
-- comentario1,
-- comentario2,
-- comentario3,
-- comentario4,
-- comentario5,
-- comentario6,
-- nota,
-- fecha_nacemiento,
-- satesfaccion_trabajo,
-- calificacion1,
-- calificacion2,
-- calificacion3,
-- calificacion4,
-- calificacion5,
-- datos_deseado,
-- cod_asistencia,
-- experiencia,
-- fase_evaluacion,
-- sueldodeseado,
-- sueldo,
-- otros,
-- is_active,
-- is_admin,
-- is_publico,
-- esta_aprobado,
-- postulante,
-- ingresadopor,
-- desaprobado,
-- fecha,
-- fechaaprobado,
-- fechaactualizacion)value 
-- ("Javier",
-- "Cajahuaman Mallcco",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "admin",
-- "90b9aa7e25f80cf4f64e990b78a9fc5ebd6cecad",
-- "",
-- "1",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "",
-- "1",
-- "1",
-- "",
-- "",
-- "",
-- "",
-- "",
-- NOW(),
-- "",
-- "");